### ISSUE TITLE
Sim?

### ISSUE THREAD

**Issue by shift-reality** [jlblancoc/claraquino#1]
Hi
Do you known some linux program to simulate/test work of this board hard and soft-ware?

**Comment by shift-reality** [comment]
And which program i can make changes in board scheme? there only pdf:(

**Comment by jlblancoc** [comment]
Hi, 

I don't know any Linux sw for that, sorry... Probably, if the schematic is ported to Proteus, that program could make a good simulation (but I didn't tested it, neither). You can, however, simulate the firmware with the free AVR Studio IDE, if that helps. 

I just uploaded the source of the 1st version of the board, for Altium, here: fcdde83d88091c6eb56d39231da76a5fe9cbb3a9

It would be great to create a Claraquino v2.0 board design, in either Proteus or Eagle, but I'm swamped with other projects, so wouldn't be able to do it for a while...

Cheers,
JL

**Comment by shift-reality** [comment]
Is Altium have export feature to kicad or some other product?
